name: Tests

on: [pull_request]

jobs:
  tests:
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [MacOS, Windows]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"

      - name: Install dependencies
        run: poetry install

      - name: Generate code from proto files
        shell: bash
        run: poetry run python -m tests.generate -v

      - name: pytest
        run: poetry run pytest
